<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit71c93f58b0a9c0299faa8d03db486d2f
{
    public static $prefixLengthsPsr4 = array (
        'G' => 
        array (
            'GameQ\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'GameQ\\' => 
        array (
            0 => __DIR__ . '/..' . '/austinb/gameq/src/GameQ',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit71c93f58b0a9c0299faa8d03db486d2f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit71c93f58b0a9c0299faa8d03db486d2f::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
